# ===== BASE DE DATOS =====
spring.datasource.url=jdbc:mysql://localhost:3306/movo_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== JWT =====
jwt.secreto=MovoSecretKey2026SuperLongSecretForJWTSigningMinimum256Bits!!
jwt.expiracion=86400000

# ===== SERVIDOR =====
server.port=8080
